### ISSUE TITLE
Contao4 - Bericht

### ISSUE THREAD

**Issue by ngdot** [fritzmg/contao-be-include-info#14]
Funktioniert alles bis auf die "Include Info" in den Einstellungen eines Elements/Artikels. 
Ist einfach leer.

**Comment by fritzmg** [comment]
Naja, dort erscheint nur etwas, wenn der Artikel oder das Element irgendwo in einem Include Element inkludiert wurde.

**Comment by ngdot** [comment]
Jo, weiß ich. Habe ich auch getan, in der Element-Übersicht steht auch das es Inkludiert ist, aber in der Element-Einstellung taucht es nicht auf.

**Comment by fritzmg** [comment]
Ok schau ich mir bei Gelegenheit mal an :). Die Extension wird aber wenn dann sowieso nur bis <= Contao 4 kompatibel bleiben (also in Contao 5 nicht mehr), zumindest in der aktuellen Form.

**Comment by ngdot** [comment]
Super, danke dir! Contao 5 LTS ist auch noch in weiter Ferne :P

**Comment by ngdot** [comment]
Sehe gerade, dass die "Include Info" in den Einstellungen eines Elements/Artikels auch in Contao 3.5 LTS fehlt.

**Comment by fritzmg** [comment]
Das "Include Info" Feld fehlt theoretisch ab Contao 3.3.0, weil es da eine nicht rückwärtskompatible Änderung in der DataContainer.php gab.

**Comment by ngdot** [comment]
Ah okay – ist meiner Meinung nach auch nicht zwingend notwendig. Habe die Ausgabe ja direkt in Element selbst. Rest funktioniert super.

**Comment by fritzmg** [comment]
https://github.com/contao/core/issues/8717

**Comment by fritzmg** [comment]
Hab's mal trotzdem für Contao 4 freigegeben.

**Comment by fritzmg** [comment]
fixed in 158cc9a5acacd12c7bf8f60ba650628c80c07788
