### ISSUE TITLE
Contao4: Cannot call abstract method Contao\Widget::generate()

### ISSUE THREAD

**Issue by ngdot** [fritzmg/contao-be-include-info#15]
Hi, unter Contao4 gibt es ein Problem mit deiner Erweiterung! Wenn ich ein Include Element erstellen will, kommt folgender Fehler: 

Internal Server Error
Cannot call abstract method Contao\Widget::generate()

Hier der Auszug aus dem error.log

> 2017-11-08 09:28:01] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction","_route":"contao_backend"},"request_uri":"https://supergeheimedomain.de/contao?act=edit&do=article&id=375&ref=MV1kA38k&rt=QxeCGJDNB2d2XqvCX4wMR5hvvwVo7e87XXsStxXn2bQ&table=tl_content","method":"HEAD"} []
> [2017-11-08 09:28:01] security.INFO: Attempting SimplePreAuthentication. {"key":"backend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
> [2017-11-08 09:28:01] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction","_route":"contao_backend"},"request_uri":"https://supergeheimedomain.decontao?act=edit&do=article&id=375&ref=MV1kA38k&rt=QxeCGJDNB2d2XqvCX4wMR5hvvwVo7e87XXsStxXn2bQ&table=tl_content","method":"GET"} []
> [2017-11-08 09:28:01] security.INFO: Attempting SimplePreAuthentication. {"key":"backend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
> [2017-11-08 09:28:01] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Cannot call abstract method Contao\\Widget::generate() at /var/www/html/vendor/fritzmg/contao-be-include-info/system/modules/be_include_info/IncludeInfoField.php:88)"} []

```

**Comment by fritzmg** [comment]
Probiere mal die aktuelle dev-master Version (https://github.com/fritzmg/contao-be-include-info/commit/f4d66b228dc7bd2a71bbc3de5fb008463c21b096).

**Comment by ngdot** [comment]
Funktioniert, danke!

**Comment by fritzmg** [comment]
Ist als `0.5.7` getagged :)
