### ISSUE TITLE
edit.gif falsch

### ISSUE THREAD

**Issue by Samson1964** [fritzmg/contao-be-include-info#6]
Das edit.gif beim Element Inhaltselement ist falsch referenziert. Geht bei mir zu /system/themes/flexible/images/edit.gif. Bei mir gibts kein flexible-Verzeichnis.

**Comment by fritzmg** [comment]
Ah, das flexible Theme ist neu in Contao 3.4. In der neuen Version gibt es das edit.gif aber eh nicht mehr, da habe ich nur mehr die Artikel verlinkt, wo das Original ist bzw. die anderen Include Elemente. 0.3.0 werde ich heute noch veröffentlichen.
